apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - db-statefulset.yaml
  - db-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - poller-deployment.yaml
